### ISSUE TITLE
Routing Errors?

### ISSUE THREAD

**Issue by markjwill** [OfficeStack/OpenSkedge#85]
Just Installed openSkedge, excited to be a part of a fellow Minnesotan's project!

Just after install both
https://openskedge/settings/ip-manifest/
https://openskedge/settings

were 404'ing so I looked in /src/OpenSkedge/AppBundle/Resources/config/routing.yml
 found lines 360-383

```
app_settings_ips:
    pattern:  /app/settings/ip-manifest/
    defaults: { _controller: OpenSkedgeBundle:IP:index }

app_settings_ip_new:
    pattern:  /app/settings/ip/new
    defaults: { _controller: OpenSkedgeBundle:IP:new }

app_settings_ip_edit:
    pattern:  /app/settings/ip/{id}/edit
    defaults: { _controller: OpenSkedgeBundle:IP:edit }
    requirements:
        id: \d+

app_settings_ip_delete:
    pattern:  /app/settings/ip/{id}/delete
    defaults: { _controller: OpenSkedgeBundle:IP:delete }
    methods: [POST]
    requirements:
        id: \d+

app_settings_edit:
    pattern:  /app/settings
    defaults: { _controller: OpenSkedgeBundle:Settings:edit }
```

Tried removing the /app bit since the urls do not have it

```
app_settings_ips:
    pattern:  /settings/ip-manifest/
    defaults: { _controller: OpenSkedgeBundle:IP:index }

app_settings_ip_new:
    pattern:  /settings/ip/new
    defaults: { _controller: OpenSkedgeBundle:IP:new }

app_settings_ip_edit:
    pattern:  /settings/ip/{id}/edit
    defaults: { _controller: OpenSkedgeBundle:IP:edit }
    requirements:
        id: \d+

app_settings_ip_delete:
    pattern:  /settings/ip/{id}/delete
    defaults: { _controller: OpenSkedgeBundle:IP:delete }
    methods: [POST]
    requirements:
        id: \d+

app_settings_edit:
    pattern:  /settings
    defaults: { _controller: OpenSkedgeBundle:Settings:edit }
```

And now everything seems to work!  If I really knew what I was doing on gitHub I'd make a pull request, but Im still learning...
